export const glossaryAdditions = [
  ["Block Height","Foundations"],["Genesis Block","Foundations"],["Node","Foundations"],["Distributed Ledger Technology (DLT)","Foundations"],["Hash / Hash Function","Foundations"],["Merkle Tree","Foundations"],["Decentralization","Foundations"],["Fork","Foundations"],["Mainnet","Foundations"],["Testnet","Foundations"],["Layer 1 (L1)","Foundations"],["Layer 2 (L2)","Foundations"],["Sidechain","Foundations"],["Cross-Chain Bridge","Foundations"],["Interoperability","Foundations"],["Immutability","Foundations"],["Consensus Mechanism","Foundations"],["Gwei","Foundations"],["Double-Spending","Foundations"],["51% Attack","Foundations"],
  ["Coin vs. Token","Assets"],["Altcoin","Assets"],["Native Coin","Assets"],["Wrapped Token","Assets"],["Utility Token","Assets"],["Security Token","Assets"],["Governance Token","Assets"],["Meme Coin","Assets"],["Circulating Supply","Assets"],["Total Supply","Assets"],["Max Supply","Assets"],["Market Capitalization (Market Cap)","Assets"],["Tokenomics","Assets"],["Burning","Assets"],["Minting","Assets"],["Airdrop","Assets"],
  ["Hot Wallet","Wallets"],["Cold Wallet","Wallets"],["Hardware Wallet","Wallets"],["Custodial Wallet","Wallets"],["Non-Custodial Wallet","Wallets"],["Multi-Signature (Multisig) Wallet","Wallets"],["Address Poisoning","Wallets"],["Derivation Path","Wallets"],["Custody","Wallets"],
  ["Proof of Work (PoW)","Mining & Consensus"],["Proof of Stake (PoS)","Mining & Consensus"],["Mining","Mining & Consensus"],["Mining Pool","Mining & Consensus"],["Hash Rate","Mining & Consensus"],["Staking","Mining & Consensus"],["Validator","Mining & Consensus"],["Delegated Proof of Stake (DPoS)","Mining & Consensus"],["Slashing","Mining & Consensus"],["Block Reward","Mining & Consensus"],["Halving","Mining & Consensus"],
  ["Order Book","Trading & Markets"],["Liquidity","Trading & Markets"],["Slippage","Trading & Markets"],["Spread","Trading & Markets"],["Market Order","Trading & Markets"],["Limit Order","Trading & Markets"],["Volatility","Trading & Markets"],["Volume","Trading & Markets"],["HODL","Trading & Markets"],["FOMO / FUD","Trading & Markets"],["Pump and Dump","Trading & Markets"],["Whale","Trading & Markets"],["Arbitrage","Trading & Markets"],["Leverage / Margin Trading","Trading & Markets"],["Liquidation","Trading & Markets"],["Copy Trading","Trading & Markets"],
  ["DeFi","DeFi"],["Liquidity Pool","DeFi"],["Liquidity Provider (LP)","DeFi"],["Yield Farming","DeFi"],["Staking Pool","DeFi"],["Impermanent Loss","DeFi"],["Automated Market Maker (AMM)","DeFi"],["Total Value Locked (TVL)","DeFi"],["Flash Loan","DeFi"],["Collateralized Debt Position (CDP)","DeFi"],["Rug Pull","DeFi"],
  ["NFT (Non-Fungible Token)","NFTs & Digital Assets"],["Fungibility","NFTs & Digital Assets"],["Minting (NFT context)","NFTs & Digital Assets"],["Metadata","NFTs & Digital Assets"],["Royalties","NFTs & Digital Assets"],["Floor Price","NFTs & Digital Assets"],["Wash Trading (NFT context)","NFTs & Digital Assets"],
  ["Smart Contract","Development"],["dApp (Decentralized Application)","Development"],["Token Standard","Development"],["EVM (Ethereum Virtual Machine)","Development"],["Solidity","Development"],["Audit (Smart Contract Audit)","Development"],["Oracle","Development"],["API (Application Programming Interface)","Development"],["RPC (Remote Procedure Call) Node/Endpoint","Development"],
  ["Ponzi Scheme","Security"],["Pyramid Scheme","Security"],["High-Yield Investment Program (HYIP)","Security"],["Seed Phrase Scam","Security"],["Approval Scam / Malicious Approval","Security"],["Fake Exchange / Clone Platform","Security"],["Pig Butchering Scam","Security"],["Recovery Room Scam","Security"],["Impersonation Scam","Security"],["Dusting Attack","Security"],["Sandwich Attack","Security"],["SIM Swap Attack","Security"],["Social Engineering","Security"],
  ["Blockchain Forensics","Forensics"],["Wallet Tracing / Fund Tracing","Forensics"],["Transaction Graph","Forensics"],["Fund Dilution","Forensics"],["Cluster Analysis / Wallet Clustering","Forensics"],["Attribution","Forensics"],["Mixer / Tumbler","Forensics"],["Peel Chain","Forensics"],["Layering","Forensics"],["Chain Hopping","Forensics"],["KYT (Know Your Transaction)","Forensics"],["On-Chain Analysis","Forensics"],["Off-Chain Analysis","Forensics"],["Blockchain Explorer","Forensics"],["Case File / Evidence Package","Forensics"],["Chain of Custody (Digital Evidence)","Forensics"],["Asset Freeze / Asset Recovery","Forensics"],
  ["KYC (Know Your Customer)","Regulation & Compliance"],["AML (Anti-Money Laundering)","Regulation & Compliance"],["FATF (Financial Action Task Force)","Regulation & Compliance"],["Travel Rule","Regulation & Compliance"],["VASP (Virtual Asset Service Provider)","Regulation & Compliance"],["Sanctions List","Regulation & Compliance"],["Regulatory Arbitrage","Regulation & Compliance"],["Unregistered Securities Offering","Regulation & Compliance"],
] as const;
